### ISSUE TITLE
Hotlinking to markers

### ISSUE THREAD

**Issue by nicomollet** [tutsplus/google-maps-api#1]
Hello

I am the author of Map Icons Collection http://mapicons.nicolasmollet.com

The scripts are using hotlinking to icons on my server.
And hotlinking is disabled on my site.
For performance reasons on my server, can you remove the call to the icons?

Kind regards

**Comment by greenweb** [comment]
@nicomollet Have you contacted Envato? The files are related to a premium course on the Google Maps API - https://code.tutsplus.com/courses/custom-interactive-maps-with-the-google-maps-api/

It's sucks that they didn't get back to you.

**Comment by adamarthurryan** [comment]
@nicomollet I've updated the course and source repository to use local copies of the icons. Thanks for bringing this to our attention. 

And @greenweb, thanks for the bump!
